spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/sbms?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: docker-compose
server:
  port: 8080